<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Truck.aspx.cs" Inherits="Truck.TruckDetails.Truck" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<link href="../../Css/style.css" rel="stylesheet" />
    <title></title>
</head>
<body>
    <h1 style="text-align: center">Manage Truck</h1>
    <form id="form1" runat="server">
        <div>
        <div class="divs">
            <table border="1" cellpadding="10" cellspacing="10" style="border-collapse: collapse" ">
             <tr>
                <td style="width: 170px">Code:<br />
                    <asp:TextBox ID="txtCode" runat="server" Width="140" />
                      <asp:RequiredFieldValidator runat="server" Color="Red" ControlToValidate="txtCode" ErrorMessage="*">
                         </asp:RequiredFieldValidator>
            
                </td>
                <td style="width: 170px">Name:<br />
                    <asp:TextBox ID="txtName" runat="server" Width="140" /> 
                    <asp:RequiredFieldValidator runat="server" ControlToValidate="txtName" ErrorMessage="*">
                       </asp:RequiredFieldValidator>
                </td>
            </tr>
             <tr>
                 <td style="width: 160px">Status:
                    <asp:DropDownList Id="drpStatus" Enabled="true" runat="server" >
                        <asp:ListItem Text="Select Status" Value="0"></asp:ListItem>
                         <asp:ListItem Text="Out Of Service" Value="1"></asp:ListItem>
                         <asp:ListItem Text="Loading" Value="2"></asp:ListItem>
                         <asp:ListItem Text="To Job" Value="3"></asp:ListItem>
                         <asp:ListItem Text="At Job" Value="4"></asp:ListItem>
                         <asp:ListItem Text="Returning" Value="5"></asp:ListItem>
                    </asp:DropDownList> 
                 </td>
                 <td style="width: 150px">Description:<br />
                     <asp:TextBox ID="txtDesc" runat="server" Width="140" />
                 </td>
            </tr>
               
            </table>
            </div>
             <div>
                <div class="divs" style="margin-top:20px"> 
                    <div style="margin-right:20px">
                         <asp:Button Text="Add" runat="server" ID="btnAdd" OnClick="btnAdd_Click" />
                    </div>
                    <div>
                         <asp:TextBox ID="txtSearch" runat="server" Width="140" />
                         <asp:Button Text="Search" runat="server" ID="btnSearch" OnClick="btnSearch_Click" />
                    </div>
                </div>
               
               <div class="divs" style="margin-top:20px">
                <asp:GridView ID="grdTruck" runat="server"  AllowSorting="true" OnSorting="grdTruck_Sorting"    
                     AutoGenerateColumns="False" ShowHeaderWhenEmpty="true" AutoGenerateEditButton="true"
                    AutoGenerateDeleteButton="true" DataKeyNames="Id"  onrowdeleting="grdTruck_RowDeleting" 
                     cellpadding="5" cellspacing="5">  
                     <HeaderStyle CssClass="gridViewHeader" />
                     <RowStyle CssClass="gridViewRow" />
                     <Columns>  
                        <asp:BoundField DataField="Code" HeaderText="Code" SortExpression="ID" />  
                        <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />  
                        <asp:BoundField DataField="Status" HeaderText="Status" SortExpression="Status" />  
                        <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />  
                    </Columns>                 
            </asp:GridView>
           </div>
          </div>
         </div>
    </form>
</body>
</html>
